Database:
  # SQLLite
  ConnectionString: "DataSource={{ db_dir }}App_{{ env }}.db"
  
#Mailing:
#
#   # Links in the email will have this base url
#   AppUrl: http://localhost:5000
#
#   Smtp:
#     Host: smtp.mailtrap.io
#     Port: 25
#     UserName: user_name
#     Password: password
#
