# This is a template your team can fill and commit to use as an example how to configure your application 
# Create one appSettings for each environment: appSettings.{Environment}.yml
# - appSettings.Development.yml
# - appSettings.Test.yml
# - appSettings.Production.yml
# Commit this file to your git repository
# don't commit appSettings.{Environment}.yml. They should be ignored in .gitignore

Url:
  # Base for complete urls: ${base}{route) example: http://yourapp.com/User/1
  # Can be used to build urls in emails or for external integrations
  Base: https://yourapp.com 

# Set where the application will listen for requests
# Urls: http://localhost:6000/;https://localhost:6001/

Database:
  # Check more database and options at connectionstrings.com
  # Sqlite
  # replace {{ input.environment }} with your environment: Development, Test, etc.
  ConnectionString: DataSource={{ db_dir }}App_{{ input.environment }}.db
  # MySql
  # ConnectionString: Server=localhost;Database=database;Uid=user;Pwd=password;
  # Postgres
  # ConnectionString: Server=localhost;Port=5432;Database=database;User Id=user;Password=password;
  # SqlServer
  # ConnectionString: Server=localhost;Database=database;User Id=user;Password=password;
  
Mailing:
#  Smtp:
#    Host: smtp.mailtrap.io
#    Port: 25
#    UserName: username
#    Password: password
#    Ssl: true

# Serilog configuration
# log levels: https://github.com/serilog/serilog/wiki/Configuration-Basics#minimum-level
# Modules: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#aspnet-core-and-ef-core-categories
Serilog:
  MinimumLevel:
    Default: Warning
#    Override:
#      Miru: Information
#      Microsoft: Information
#      Microsoft.AspNetCore: Information
#      Microsoft.EntityFrameworkCore.Database.Command: Information # Show SQL
#      Microsoft.Hosting: Information
#      Hangfire: Information
