Database:
  ConnectionString: "DataSource={{ db_dir }}App_test.db"

#Mailing:
#  AppUrl: http://localhost:5000
#  Smtp:
#    Host: smtp.mailtrap.io
#    Port: 25
#    UserName: 3d9492b2a84d70
#    Password: 3bc5fdad64b57e